apiVersion: v1
kind: Service
metadata:
  labels:
    app: app-aware-nsm
  name: app-aware-nsm
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 31500
  selector:
    app: app-aware-nsm
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-aware-nsm
  name: app-aware-nsm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-aware-nsm
  template:
    metadata:
      labels:
        app: app-aware-nsm
    spec:
      containers:
      - name: app-aware-nsm
        image: ghcr.io/nextworks-it/app-aware-net-slice-manager/app-aware-nsm:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
      imagePullSecrets:
      - name: regcred