FROM python:3.8-slim-buster

RUN apt-get update -y && apt-get install -y python3-pip

VOLUME /root/.kube/config

WORKDIR /app-aware-nsm

COPY apis/ apis/
COPY core/ core/
COPY app.py app.py
COPY setup.py setup.py
COPY requirements.txt requirements.txt

VOLUME /app-aware-nsm/config.ini

RUN pip3 install -r requirements.txt

EXPOSE 5000

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]